### ISSUE TITLE
Foreign key izmena

### ISSUE THREAD

**Issue by Etheraex** [Etheraex/SBP#2]
Pokusaj promene RasaFK kod Lik entiteta baca 

`Error dehydrating property value for SBP_Data.Models.Lik.Rasa ---> NHibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing or set cascade action for the property to something that would make it autosave`

Odkomentarisite kod u Test2 dugmetu da vidite gresku.

**Comment by Mr-357** [comment]
ok mozda imamo mali problem sa createorupdate u DTO

pazi sad ovako, google kaze da ovu gresku fixujes tako sto dodas cascade tamo u mapiranja i ja lepo dodam cascade i opa bato iskoci mi novi vilenjak u rasa tabelu (sto je naravno no-no)

e sad fora je sto ne mozemo da modifikujemo DTO time sto mu pridruzimo DTO npr kod Lika njegova rasa je tip modela a ne DTO, mislim da treba da izmenimo da sve bude DTO samo sto posle ne znam kako ce to tacno da radi kod update i da li ce da radi, nesto smo se tu zajebali

alternativno treba nam fja koja kad ucita model preko DTOa moze da nam vrati entitet koji je ucitan (aka modifikujemo createorupdate da kad radi create setuje ID na nesto ako je setovan u klasi)

**Comment by Mr-357** [comment]
```C#
public override object CreateOrUpdate(object input)
        {
            Vilenjak i = null;
            if (input != null)
                i = input as Vilenjak;
            else if (i == null || input == null)
                i = new Vilenjak();
            if (ID != null || ID != 0)
                i.Id = ID;
            i.Koristi = Koristi;
            i.NivoEnergije = NivoEnergije;
            return i;

        }
```

novi izgled create or update, ovo mi ima smisla i guess, za sada cu da zatvorim issue jer ovo ga fixuje ali trebalo bi i u ostalim klasama da se uradi

btw mora da padne refactor neki imamo dosta "ponavljanja" koda

**Comment by Mr-357** [comment]
e da treba bazu da fixujemo 
![image](https://user-images.githubusercontent.com/37952904/58731633-8dbe6b80-83ef-11e9-9f1f-3d4cdac036cf.png)
oopsie
