### ISSUE TITLE
put akcije ne koriste prosleden id

### ISSUE THREAD

**Issue by Stefan1911** [Etheraex/SBP#6]
nase put akcije odprilike ovako izgledaju
        public void Put(int id, [FromBody]IgracDTO igrac)
        {
            DTOManager.Instance.UpdateEntity(igrac);
        }
i uopste ne koriste onaj id sto je prosleden posto se on nalazi u prosledenom igracu.
tako da bi ovo ladno moglo da bude i post al mislim da nije bitno i da mozemo samo da ga ostavimo ovako, onda bi koristili post za ovo cisto radi konvencij. Sta mislite da prebacimo ovu akciju u post ili da je ostavimo ovako ?

**Comment by Mr-357** [comment]
ovo treba da radi tako sto nadje objekat sa ID id i modifikuje ga sa podacima iz tela, mozda bolje da napravimo fju u dtomanager koja ce da radi bas to, nadje dto koji nam treba, proveri sta mu je promenjeno (osim npr listi koje sadrzi taj objekat), promeni sta treba i sacuva, tehnicki kao ne bi trebalo da saljes ceo objekat odnosno ID objekta unutar samog objekta

**Comment by Mr-357** [comment]
btw oni ne salju view u njihovom DTO objektu, mozda ne bi trebalo ni mi?

**Comment by Stefan1911** [comment]
public void Put(int id, [FromBody]IgracDTO igrac)
        {
            igrac.ID = id;
            DTOManager.Instance.UpdateEntity(igrac);
        }

a ovako da ga resimo ?
ovako korisnik ne bi morao da salje id unutar tela prosledjenog igraca

**Comment by Mr-357** [comment]
to ce verovatno da radi samo sto ce verovatno sve liste unutar toga da se sjebu jer nam ne radi ona createorupdate fja za liste i reference

**Comment by Mr-357** [comment]
posto sad JSON ignorise ove atribute (id, entity type), mora da se prosledi ID rucno PUT-u tako da smo ga resili
